target 'ABFRealmSearchViewControllerExample' do
  pod 'Realm', :git => 'https://github.com/realm/realm-cocoa', :branch => 'tg-async-query'
  pod 'RealmSFRestaurantData'
  pod 'TOWebViewController'
end

target 'ABFRealmSearchViewControllerExampleTests' do
  pod 'Realm/Headers', :git => 'https://github.com/realm/realm-cocoa', :branch => 'tg-async-query'
end

